### ISSUE TITLE
num_cpus final_number_of_files

### ISSUE THREAD

**Issue by albertma-evotec** [vibudh2209/D2#15]
for `python smile_simplification.py -sfp path_smile_folder/smile_folder -tp num_cpus -tn final_number_of_files`
what do num_cpus and final_number_of_files refer to?

Isn't the final_number_of_files same as the number of .smi files I have prepared in the smile_folder?

It would be nice to have a bit more details about what each argument is referring to.

Thanks

**Comment by fgentile89** [comment]
Hi, 
as indicated  in our manual ("Reorganize the SMILES files into a number of evenly populated files equal to the number of CPUs used for phase 1 (see below)") smile_simplification reorganizes the files you have in smile_folder into a number of files which is equal to how many cpus you want to use in phase_1, in order to make the sampling maximally efficient. So if you want to use 60 cpus, use final_number_of_files 60 (and num_cpus as well). Folloqing your and others' input, we are currently working on a more detailed version of the manual as well as a more automated version of the program.

Cheers

Francesco
